### ISSUE TITLE
htmx 2.0 default config

### ISSUE THREAD

**Issue by iamhold3n** [roniemartinez/tauri-plugin-htmx#9]
Thanks for making this plugin!

I ran into some issues with the latest version of htmx, as selfRequestsOnly is true by default. Using `command:function` fails the verifyPath function in htmx (that is executed before `htmx:beforeSend` is triggered) and you get an `htmx:invalidPath` error unless this setting is disabled.

Adding `<meta name="htmx-config" content='{"selfRequestsOnly":false}' />` to the head in index.html fixes this.

**Comment by roniemartinez** [comment]
Thanks @iamhold3n 

I haven't tested this myself but it looks like this meta is required based on the documentation. Would you be happy to update the README and submit a PR?
